{{- if not .Values.global.experimental_native_ingress }}
apiVersion: v1
kind: Secret
metadata:
  name: deis-router-dhparam
  labels:
    heritage: deis
type: Opaque
data:
  dhparam: {{ if not (empty .Values.dhparam) }}{{ .Values.dhparam }}{{ else }}LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KTUlJQ0NBS0NBZ0VBbFhvcCtSdDN5elJhQ0VCWVJXd2E0ak1vL3NRaGt6VHdGMkhKRUZ6N3d3dXVacURHanBMcAoyQkZzK3p2dEdaYzdvaWR4MGxaemQ1dFBndVppRmllSjRvV0F2ZmFrejRJZWZ6d2tBclRBcG54WUdTK0g5aEZXClZKM2t3TzhpOFRLVVB0UXpocGN1Qm1GT09DZ2t6ZDJETHhESkc5Mmd3UXpRVTBmTWpoMFNxbnNuSXdKYWdOYzIKZHN1QnRvay9pZC9xUDFnT09VOHR0aDlObzdIV0ZSSXVaVVc0VXYvbHlybnl5anJHS2R3Zk9nZzdGT0RWNzh4KwpHVE00R1RBRkd5R1drZ0pBQldjQ21Ld3pmakV4MFNaalQ1NkNJRHBIaGxMRDNWdXNUVHFRdGhWYTlCTi9HZzk3Cmd6WjkzdStpdlU3Wnl5TEJaTEFaSXprT2swUVgrOTU3SXcrK1hOLzA5SUd1aTdOWEtkOXZ6YjQ0Wk8xRVZaWVcKZm02eHhUdFNLQVVXNFJSZVVlWHBOUlNjT0VMT0ZJdFU3c1FKaDFYOXZIQjRubXdYNlVuZzRhVjMyV21wTXMrVwpVYmgzcTFIN3YxMFdyK1FXZXR3aGd6Mk9IQytMVDV4VHp1bWVITnRobzZIYklIdHRSb3ZsNEkxQjYvaVdpMFBnCkZ6TU5qNTZkQjFYYldMVjUrOVZBZ1VwNlUzZVFjVDFoMTRwVGtYdWl2S2tMcVhSUXJEZGFkTmNnS0RCMHkvaHYKOUtpWnEzVjNkbXFBSnVIMExpQmhQdU9BZk5ZUTZzQzlYSXJhclNEanoxdmNpeGkxR1RFNGZvckRpMnJMZXdhbApRMFpOVHdGREEwYmc2UTUxQU1PQ0hLb2JMMHhTZjRHTzhCMUt6ODk2d1JIQzNKb2tMeHJ6R01zQ0FRST0KLS0tLS1FTkQgREggUEFSQU1FVEVSUy0tLS0tCg=={{ end }}
{{ end }}{{/* if not .Values.global.experimental_native_ingress */}}
